version: '3.8'

services:
  # 1. 데이터베이스 서버 설정
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bereal_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1020  # 원하는 비밀번호로 수정하세요
    ports:
      - "5432:5432"

  # 2. 장고 서버 설정
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=bereal_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1020  # 위 db 설정과 똑같이 입력
      - DATABASE_HOST=db                 # 중요: localhost가 아니라 'db' 서비스 이름 사용
      - DATABASE_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: